# Conditional Probability

Suppose that you are playing a game of two dice and you want to bet that the first die will show a 6. A friend of yours rolls the dice and tells you that the sum of the two dice is 7. What is the probability that the first die shows a 6 _given_ that the sum of the two dice is 7? Would this additional information help you when deciding whether to bet on the first die showing a 6?


Let $A$ and $B$ be two events. The conditional probability of $A$ given $B$ is defined as

$$
P(A|B) = \frac{P(A \cap B)}{P(B)}
$$

We read $P(A | B)$ as "the probability of $A$ given $B$".

## Independence of Two Events

## Independence of Two Events

Two events $A$ and $B$ are said to be independent if

$$
P(A \cap B) = P(A) \cdot P(B)
$$


## Independence and Conditional Probability

Show that the definition of independence in @def-independence-AB is equivalent to the following:

1. $P(A|B) = P(A)$
2. $P(B|A) = P(B)$

## Implications of Independence

Show that if $A$ and $B$ are independent, then the following statements are true:

1. $A$ and $B^c$ are independent
2. $A^c$ and $B$ are independent
3. $A^c$ and $B^c$ are independent


## Disjoint Events and Independence

Let $A$ and $B$ be two events such that $P(A) > 0$ and $P(B) > 0$. Show that if $A$ and $B$ are disjoint, then they are not independent.

## Mutual Independence

## Mutual Independence

Events $A_1, A_2, \ldots, A_n$ are said to be mutually independent if for every subset $I \subseteq \{1, 2, \ldots, n\}$ we have

$$
P\left(\bigcap_{i \in I} A_i\right) = \prod_{i \in I} P(A_i)
$$

For example for $n=3$ we have that $A_1$, $A_2$, and $A_3$ are mutually independent if _all_ of the following conditions hold:

$$
\begin{align*}
P(A_1 \cap A_2) &= P(A_1) \cdot P(A_2) \\
P(A_1 \cap A_3) &= P(A_1) \cdot P(A_3) \\
P(A_2 \cap A_3) &= P(A_2) \cdot P(A_3) \\
P(A_1 \cap A_2 \cap A_3) &= P(A_1) \cdot P(A_2) \cdot P(A_3) \\
\end{align*}
$$

## Mutual Independence and Pairwise Independence

Consider a sample space with 9 equally likely outcomes, each consisting of a triple $(i, j, k)$ where $i, j, k \in \{1, 2, 3\}$.

$$
\Omega = \left\{
    \begin{align*}
    (1, 1, 1), (2, 2, 2), (3, 3, 3) \\
    (1, 2, 3), (1, 3, 2), (3, 2, 1) \\
    (3, 1, 2), (2, 1, 3), (2, 3, 1) \\
    \end{align*}
\right\}
$$

Consider the following events $A_i = \{\text{i-th place of the outcome is 1}\}$. Are the events $A_1$, $A_2$, and $A_3$ pairwise independent? Are they mutually independent?

## Bayes' Theorem


## Bayes' Theorem

Let $A$ and $B$ be two events such that $P(A) > 0$ and $P(B) > 0$. Then

$$
P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}
$$

Furthermore, let $A_1, A_2, \ldots, A_n$ be a partition of the sample space $\Omega$. A partition is a collection of disjoint events such that their union is the entire sample space:

$$
A_i \cap A_j = \emptyset \quad \text{for all } i \neq j \quad \text{and} \quad \bigcup_{i=1}^n A_i = \Omega
$$

For any event $B$ such that $P(B) > 0$, we have

$$
P(A_i|B) = \frac{P(B|A_i) \cdot P(A_i)}{\sum_{j=1}^n P(B|A_j) \cdot P(A_j)}
$$

To understand the derivation of Bayes' Theorem, see that it holds for a very simple partition. The collection of events $A$ and $A^c$ is a partition of the sample space. In this case, Bayes' Theorem becomes

$$
P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B|A) \cdot P(A) + P(B|A^c) \cdot P(A^c)}
$$

## Total Probability and Complements

Let $A$ and $B$ be some events such that $P(A) > 0$ and $P(B) > 0$. Show that

$$
P(B) = P(B|A) \cdot P(A) + P(B|A^c) \cdot P(A^c)
$$

## Total Probability Theorem

Let $A_1, A_2, \ldots, A_n$ be a partition of the sample space $\Omega$. For any event $B$ such that $P(B) > 0$, we have

$$
P(B) = \sum_{i=1}^n P(B|A_i) \cdot P(A_i)
$$

## Roadside Drug Tests

Imagine a city called Virtue City with 10,000 drivers in any day. 100 of the drivers drive under the influence of drugs.

The police department introduces a new test for narcotics that has a 95 percent probability of correctly identifying a person who has used narcotics (true positive). There is a one percent probability of falsely identifying a person who has not used narcotics as having used them (false positive).

The police stop a driver, his test comes back positive, and the driver's car is confiscated. The police claim that there is a 95 percent probability that the driver is a drug user. The driver objects and says that the probability of him being a drug user is much lower. Who is right?

Approach this problem in two ways:

- Counting
    - How many people will have a positive test result if all 10,000 citizens are tested?
    - What proportion of the positive tests belong to actual drug users?
- Apply Bayes' Theorem

## Spam Filtering

If you have ever used email, then you have probably encountered spam emails. Spam emails are unsolicited messages that are commonly sent in bulk to many recipients. Most email service providers try to protect their users from spam by filtering out these messages. One way to do this is to train an algorithm to recognize spam emails based on the content of the email.

Suppose that the filter receives an email containing the word "Inheritance". Suppose that 5 percent of spam emails contain this word, while it is only present in 0.1 percent of non-spam emails. Suppose that 80 percent of the emails that the filter receives are spam.

What is the probability that an email containing the word "Inheritance" is spam?

## Decomposition of the Total Probability

Prove the following statements:

1. $P(B) = 1 \implies P(A|B) = P(A)$ for any event $A$.
2. $A \subset B \implies P(B|A) = 1$ and $P(A|B) = P(A)/P(B)$
3. If $A \cap B = \emptyset$

$$
P(A | A \cup B) = \frac{P(A)}{P(A) + P(B)}
$$

## Chain Rule

Let $A$, $B$, and $C$ be events such that $P(C) > 0$ and $P(B \cap C) > 0$. Then

$$
P(A \cap B \cap C) = P(A|B\cap C) P(B|C) P(C)
$$

## Quality Control

A factory produces light bulbs. To ensure the quality of the bulbs shipped to customers, the factory has a quality control system that checks a sample of the bulbs before they are shipped. Consider a shipment of 100 bulbs. You take a sample (without replacement) of 5 bulbs and stop the shipment if you find that at least one of the sampled bulbs are defective. Suppose that a shipment contains 20 defective light bulbs. What is the probability that the shipment will be stopped?

In [ ]:
#ex-class
# Simulate a sample from a shipment of 100 light bulbs
import numpy as np

sample_size = 5
repetitions = 10_000

np.random.seed(42)

# 0 represents a good light bulb, 1 represents a defective light bulb
shipment = np.array([0] * 80 + [1] * 20)

print("The shipment of light bulbs")
print(shipment)
print("\n")

rejections = 0

print("Some of the selected samples")

for i in range(repetitions):
    sample = np.random.choice(shipment, size = sample_size, replace = False)
    
    # Print the sample once every 1000 repetitions
    if i % 1000 == 0:
        print(sample)
        
    if np.sum(sample) > 0:
        rejections += 1

print("\n")
print(f"The proportion of shipments rejected is {rejections / repetitions}")

The shipment of light bulbs
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Some of the selected samples
[1 0 0 0 0]
[0 0 1 0 0]
[0 1 0 0 0]
[0 1 1 1 1]
[1 0 0 0 0]
[0 0 0 0 1]
[1 0 0 0 0]
[1 0 0 1 0]
[0 0 0 0 0]
[0 0 0 0 0]


The proportion of shipments rejected is 0.6739

In [ ]:
#ex-class
# Compute the probability of a shipment being rejected

## A Bifurcation in the Road

A tourist stands at a bifurcation in the road and does not know which is the correct way to go. He asks two passersby. Each passerby points him in the correct direction with probability 0.7 independently of each other.
We want to propose a strategy for the tourist to decide which way to go.

- Strategy 1: If the two passersby point in the same direction, the tourist follows that direction. If they point in different directions, the tourist chooses randomly.
- Strategy 2: The tourist decides to follow the direction of the first passerby only.
- Strategy 3: The tourist decides at random.

- Which strategy would you recommend? Decide this by calculating the probability of the tourist going in the correct direction for each strategy.
- Simulate the three strategies and estimate the probability of the tourist going in the correct direction. For the sake of the simulation, assume that the correct direction is the first one.

In [ ]:
#ex-class
import pandas as pd
import numpy as np

# Setup the simulation
repetitions = 10_000

np.random.seed(42)

# Simulate the third strategy

df = pd.DataFrame({
    "passerby1": np.random.choice([1, 2], size = repetitions, p = [0.7, 0.3]),
    "passerby2": np.random.choice([1, 2], size = repetitions, p = [0.7, 0.3]),
    "random_choice": np.random.choice([1, 2], size = repetitions, p = [0.5, 0.5])
})

# Checks if the two passerby agree on the direction. If yes, then take the direction of the first passerby 
# (both are equal). If not, then take the random direction

df["strategy1"] = np.where(
    df["passerby1"] == df["passerby2"],
    df["passerby1"],
    df["random_choice"]
)

df.head()

   passerby1  passerby2  random_choice  strategy1
0          1          1              2          1
1          2          1              1          1
2          2          1              1          1
3          1          1              2          1
4          1          1              1          1

In [ ]:
#ex-class
print("Strategy 1 success rate: ", (df["strategy1"] == 1).sum() / repetitions)
print("Strategy 2 success rate: ", (df["passerby1"] == 1).sum() / repetitions)
print("Strategy 3 success rate: ", (df["random_choice"] == 1).sum() / repetitions)

Strategy 1 success rate:  0.7046
Strategy 2 success rate:  0.7113
Strategy 3 success rate:  0.4978

## The Monty Hall Game

![The Monty Hall Game](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Monty_open_door.svg/300px-Monty_open_door.svg.png)


Imagine a game with three doors. Behind one of the doors is a car and behind the other two are goats. The game is played in two stages.

- First you choose a door.
- The host, _who knows what is behind each door_, opens one of the other two doors to reveal a goat.
- You are then given the opportunity to switch to the other unopened door or stay with your original choice.

Which strategy has a higher probability of winning the car? Should you switch or should you stay with your original choice? Compute the probabilities of winning the car under each strategy.

In [ ]:
#ex-class
# Simulation of the Monty Hall problem

# Setup the simulation
repetitions = 10_000

np.random.seed(42)

# Simulate the choices of the player

df = pd.DataFrame({
    "first_choice": np.random.choice([1, 2, 3], size = repetitions),    
})

df["opened_door"] = np.where(
    # If the player chose door 1 (the door with the car)
    (df["first_choice"] == 1),
    # , then the opened door is randomly chosen from doors 2 and 3
    np.random.choice([2, 3], size = repetitions),
    # Otherwise
    np.where(
        # If the player chose door 2
        (df["first_choice"] == 2),
        # , then the opened door is 3 (the host does not open the door with the car)
        3,
        # Otherwise the opened door is
        2
    )
)

df["switch_choice"] = np.where(
    # If the opened door was 2 and the player chose 1
    (df["opened_door"] == 2) & (df["first_choice"] == 1),
    # , then the switched choice is 3
    3,
    # Otherwise
    np.where(
        # If the opened door was 3 and the player chose 1
        (df["opened_door"] == 3) & (df["first_choice"] == 1),
        # , then the switched choice is 2
        2,
        # Otherwise the switched choice is 1
        1
    )
)

df.head(n = 20)

    first_choice  opened_door  switch_choice
0              3            2              1
1              1            3              2
2              3            2              1
3              3            2              1
4              1            2              3
5              1            3              2
6              3            2              1
7              2            3              1
8              3            2              1
9              3            2              1
10             3            2              1
11             3            2              1
12             1            2              3
13             3            2              1
14             2            3              1
15             1            3              2
16             2            3              1
17             2            3              1
18             2            3              1
19             2            3              1

In [ ]:
#ex-class
print("No switching wins", (df["first_choice"] == 1).mean())
print("Switching wins", (df["switch_choice"] == 1).mean())

No switching wins 0.3354
Switching wins 0.6646

## The Executive's Dilemma

Consider the following problem: A struggling company need to reduce its executive workforce from three executives to only one. The company has three executives: Alice, Bob, and Charlie. The company president decides to leave the decision of whom to keep to chance.

The president does not want to tell the executives who is remaining until the decision is announced. Alice insists, however, and asks the president to tell her at least the name of one person who is sacked. The president reminds Alice that he will reveal the name of the person remaining and also tells her that Bob is sacked.

Alice is happy because she thinks that the probability of her remaining given this information is $1/2$ instead of $1/3$ (without the information). Is Alice's reasoning correct?

The example here is a reformulation of the famous [Prisoner's Dilemma](https://en.m.wikipedia.org/wiki/Three_prisoners_problem).